spring:
  application:
    name: Service-Api-Gateway
  cloud:
    gateway:
        routes:
          - id: BLOG-SITE-SERVICE
            uri: lb://BLOG-SITE-SERVICE
            predicates:
              - Path=/api/v1.0/blogsite/blog/**
            filters:
              - AuthenticationFilter

          - id: identity-service
            uri: lb://IDENTITY-SERVICE
            predicates:
              - Path=/api/v1.0/blogsite/user/**
              
server:
  port: 8086

#Eureka configuration 
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
